### ISSUE TITLE
Investigate prototyping kit refactor

### ISSUE THREAD

**Issue by alec-hamilton-ons** [ONSdigital/prototype-kit#59]
SPIKE

The prototyping kit is becoming quite stale. It is quite brittle and inflexible in it's implementation and probably needs a refactor to make it more suitable for how it is currently used today.

**Comment by yatesn** [comment]
Raise at the next monthly forum

Keen to get a view from IxD @Majsol (@LaurenDowling potentially had some good ideas before JB left?)

**Comment by liammcmurray** [comment]
So happy to see this progressing.
I was talking with the Head of IxD for the Gov.uk Design System this week and he mentioned that several local govs, charities, and overseas gov departments already extend their design system using the undocumented plugin functionality - https://github.com/alphagov/govuk-prototype-kit-docs/issues/188

It could be a way forward that instead of maintaining our own completely separate design system - we instead piggyback on tried and tested patterns and simply develop specific patterns for ONS...

The IxD community here is really keen to be involved in any discussions about this - we need to agree the best and most sustainable way forward ⚡

**Comment by yatesn** [comment]
@JNATION85 to speak to @liammcmurray

**Comment by alessioventuriniAND** [comment]
The investigation has already been done and three tickets have been created for us to work on.
